### ISSUE TITLE
Generic tagged unions

### ISSUE THREAD

**Issue by callumforrester** [wyfo/apischema#207]
Is it possible to make tagged unions of generic classes? From [this tutorial](https://wyfo.github.io/apischema/examples/subclass_tagged_union/) I have produced the following:

```python

_alternative_constructors: dict[type, list[Callable]] = defaultdict(list)
Func = TypeVar("Func", bound=Callable)


def alternative_constructor(func: Func) -> Func:
    _alternative_constructors[get_type_hints(func)["return"]].append(func)
    return func


def rec_subclasses(cls: type) -> Iterator[type]:
    """Recursive implementation of type.__subclasses__"""
    for sub_cls in cls.__subclasses__():
        yield sub_cls
        yield from rec_subclasses(sub_cls)


Cls = TypeVar("Cls", bound=type)


def as_tagged_union(cls: Cls) -> Cls:
    def serialization() -> Conversion:
        serialization_union = new_class(
            cls.__name__,
            (TaggedUnion,),
            exec_body=lambda ns: ns.update(
                {
                    "__annotations__": {
                        sub.__name__: Tagged[sub] for sub in rec_subclasses(cls)  # type: ignore
                    }
                }
            ),
        )
        return Conversion(
            lambda obj: serialization_union(**{obj.__class__.__name__: obj}),
            source=cls,
            target=serialization_union,
            # Conversion must not be inherited because it would lead to infinite
            # recursion otherwise
            inherited=False,
        )

    def deserialization() -> Conversion:
        annotations: dict[str, Any] = {}
        deserialization_namespace: dict[str, Any] = {"__annotations__": annotations}
        for sub in rec_subclasses(cls):
            annotations[sub.__name__] = Tagged[sub]  # type: ignore
            # Add tagged fields for all its alternative constructors
            for constructor in _alternative_constructors.get(sub, ()):
                # Build the alias of the field
                alias = to_pascal_case(constructor.__name__)
                # object_deserialization uses get_type_hints, but the constructor
                # return type is stringified and the class not defined yet,
                # so it must be assigned manually
                constructor.__annotations__["return"] = sub
                # Add constructor tagged field with its conversion
                annotations[alias] = Tagged[sub]  # type: ignore
                deserialization_namespace[alias] = Tagged(
                    conversion(
                        # Use object_deserialization to wrap constructor as deserializer
                        deserialization=object_deserialization(
                            constructor, type_name(alias)
                        )
                    )
                )
        # Create the deserialization tagged union class
        deserialization_union = new_class(
            cls.__name__,
            (TaggedUnion,),
            exec_body=lambda ns: ns.update(deserialization_namespace),
        )
        return Conversion(
            lambda obj: get_tagged(obj)[1], source=deserialization_union, target=cls
        )

    deserializer(lazy=deserialization, target=cls)
    serializer(lazy=serialization, source=cls)
    return cls

T = TypeVar("T")


@as_tagged_union
class Drawing(Generic[T]):

    def points(self) -> AsyncIterable[T]:
        raise NotImplementedError


@dataclass
class Line(Drawing[T]):
    start: T
    stop: T
    step: T = field(default=1, metadata=schema(exc_min=0))

    async def points(self) -> AsyncIterable[T]:
        point = self.start
        while point <= self.stop:
            yield point
            point += self.step


@alternative_constructor
def sized_line(
    start: T, stop: T, size: Annotated[T, schema(min=1)]
) -> "Line[T]":
    return Line(start=start, stop=stop, step=(stop - start) / (size - 1))


@dataclass
class Concat(Drawing[T]):
    left: Drawing[T]
    right: Drawing[T]

    async def points(self) -> AsyncIterable[T]:
        async for point in self.left.points():
            yield point
        async for point in self.right.points():
            yield point


def echo(drawing: Drawing[str] = None) -> Optional[Drawing[str]]:
    return drawing

drawing_schema = graphql_schema(query=[echo])
assert (
    graphql.utilities.print_schema(drawing_schema)
    == """\
type Query {
  echo(drawing: DrawingInput): Drawing
}

type Drawing {
  Line: Line
  Concat: Concat
}

type Line {
  start: Float!
  stop: Float!
  step: Float!
}

type Concat {
  left: Drawing!
  right: Drawing!
}

input DrawingInput {
  Line: LineInput
  SizedLine: SizedLineInput
  Concat: ConcatInput
}

input LineInput {
  start: Float!
  stop: Float!
  step: Float! = 1
}

input SizedLineInput {
  start: Float!
  stop: Float!
  size: Float!
}

input ConcatInput {
  left: DrawingInput!
  right: DrawingInput!
}
"""
)

query = """\
{
echo(drawing: {
    Concat: {
        left: {
            SizedLine: {
                start: 0, stop: 12, size: 3
            },
        },
        right: {
            Line: {
                start: 12, stop: 13
            },
        }
    }
}) {
    Concat {
        left {
            Line {
                start stop step
            }
        }
        right {
            Line {
                start stop step
            }
        }
    }
}
}
"""

assert graphql.graphql_sync(drawing_schema, query).data == {
    "echo": {
        "Concat": {
            "left": {"Line": {"start": 0.0, "stop": 12.0, "step": 6.0}},
            "right": {"Line": {"start": 12.0, "stop": 13.0, "step": 1.0}},
        }
    }
}
```

Which gives the following error:

```
Traceback (most recent call last):
  File "/dls/science/users/######/projects/apischema-dev/demo.py", line 140, in <module>
    drawing_schema = graphql_schema(query=[echo])
  File "/dls/science/users/######/projects/apischema-dev/venv/lib/python3.9/site-packages/apischema/graphql/schema.py", line 960, in graphql_schema
    return graphql.GraphQLSchema(
  File "/dls/science/users/######/projects/apischema-dev/venv/lib/python3.9/site-packages/graphql/type/schema.py", line 208, in __init__
    collect_referenced_types(query)
  File "/dls/science/users/######/projects/apischema-dev/venv/lib/python3.9/site-packages/graphql/type/schema.py", line 423, in collect_referenced_types
    collect_referenced_types(field.type)
  File "/dls/science/users/######/projects/apischema-dev/venv/lib/python3.9/site-packages/graphql/type/schema.py", line 422, in collect_referenced_types
    for field in named_type.fields.values():
  File "/dls/science/users/######/projects/apischema-dev/venv/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/dls/science/users/######/projects/apischema-dev/venv/lib/python3.9/site-packages/graphql/type/definition.py", line 769, in fields
    raise TypeError(f"{self.name} fields cannot be resolved. {error}")
TypeError: Drawing fields cannot be resolved. Missing name for <class '__main__.Line'>
```

**Comment by wyfo** [comment]
Thank to your issue, I've found a bug that I've just fixed (#210). A new patch, v0.15.7 has been released with the fix. It has to be installed to execute the answer.

Generic tagged unions are a little bit more complex than the documentation example, but are still possible. 
Two modifications needs to be done:
- the tagged union conversion needs to be made generic
- models needs to have a [generic type_name](https://wyfo.github.io/apischema/json_schema/#set-reference-name), or at least a `type_name` registered for each possible specialization (`settings.default_type_name` can also be used).

Indeed, GraphQL doesn't support Generic, so each type must have a unique name (generated types for alternative constructors too).

Here is a proposition to modify the tutorial : 
```python
from collections import defaultdict
from collections.abc import AsyncIterable, Callable, Iterator
from dataclasses import dataclass, field
from types import new_class
from typing import Annotated, Any, Generic, Optional, TypeVar, get_type_hints

import graphql

from apischema import deserializer, schema, serializer, type_name
from apischema.conversions import Conversion
from apischema.graphql import graphql_schema
from apischema.metadata import conversion
from apischema.objects import object_deserialization
from apischema.tagged_unions import Tagged, TaggedUnion, get_tagged
from apischema.utils import to_pascal_case

_alternative_constructors: dict[type, list[Callable]] = defaultdict(list)
Func = TypeVar("Func", bound=Callable)


def alternative_constructor(func: Func) -> Func:
    _alternative_constructors[get_type_hints(func)["return"]].append(func)
    return func


def rec_subclasses(cls: type) -> Iterator[type]:
    """Recursive implementation of type.__subclasses__"""
    for sub_cls in cls.__subclasses__():
        yield sub_cls
        yield from rec_subclasses(sub_cls)


generic_name = type_name(
    lambda cls, *args: cls.__name__
    + "".join(arg.__name__[0].upper() + arg.__name__[1:] for arg in args)
)

Cls = TypeVar("Cls", bound=type)


def as_tagged_union(cls: Cls) -> Cls:
    params = tuple(getattr(cls, "__parameters__", ()))
    tagged_union_bases: tuple = (TaggedUnion,)
    if params:
        tagged_union_bases = (TaggedUnion, Generic[params])
        generic_name(cls)
        prev_init_subclass = getattr(cls, "__init_subclass__", None)

        def __init_subclass__(cls, **kwargs):
            if prev_init_subclass is not None:
                prev_init_subclass(**kwargs)
            generic_name(cls)

        cls.__init_subclass__ = classmethod(__init_subclass__)

    def with_params(cls: type) -> Any:
        return cls[params] if params else cls

    def serialization() -> Conversion:
        annotations = {
            # Assume that subclasses have same generic parameters than cls
            sub.__name__: Tagged[with_params(sub)]
            for sub in rec_subclasses(cls)
        }
        namespace = {"__annotations__": annotations}
        tagged_union = new_class(
            cls.__name__, tagged_union_bases, exec_body=lambda ns: ns.update(namespace)
        )
        return Conversion(
            lambda obj: tagged_union(**{obj.__class__.__name__: obj}),
            source=with_params(cls),
            target=with_params(tagged_union),
            # Conversion must not be inherited because it would lead to
            # infinite recursion otherwise
            inherited=False,
        )

    def deserialization() -> Conversion:
        annotations: dict[str, Any] = {}
        namespace: dict[str, Any] = {"__annotations__": annotations}
        for sub in rec_subclasses(cls):
            # Assume that subclasses have same generic parameters than cls
            annotations[sub.__name__] = Tagged[with_params(sub)]
            # Add tagged fields for all its alternative constructors
            for constructor in _alternative_constructors.get(sub, ()):
                # Build the alias of the field
                alias = to_pascal_case(constructor.__name__)
                # object_deserialization uses get_type_hints, but the constructor
                # return type is stringified and the class not defined yet,
                # so it must be assigned manually
                constructor.__annotations__["return"] = with_params(sub)
                # Use object_deserialization to wrap constructor as deserializer
                deserialization = object_deserialization(constructor, generic_name)
                # Add constructor tagged field with its conversion
                annotations[alias] = Tagged[with_params(sub)]
                namespace[alias] = Tagged(conversion(deserialization=deserialization))
        # Create the deserialization tagged union class
        tagged_union = new_class(
            cls.__name__, tagged_union_bases, exec_body=lambda ns: ns.update(namespace)
        )
        return Conversion(
            lambda obj: get_tagged(obj)[1],
            source=with_params(tagged_union),
            target=with_params(cls),
        )

    deserializer(lazy=deserialization, target=cls)
    serializer(lazy=serialization, source=cls)
    return cls


T = TypeVar("T")


@generic_name
@as_tagged_union
class Drawing(Generic[T]):
    def __init_subclass__(cls):
        generic_name(cls)

    def points(self) -> AsyncIterable[T]:
        raise NotImplementedError


@dataclass
class Line(Drawing[T]):
    start: T
    stop: T
    step: T = field(default=1, metadata=schema(exc_min=0))

    async def points(self) -> AsyncIterable[T]:
        point = self.start
        while point <= self.stop:
            yield point
            point += self.step


@alternative_constructor
def sized_line(start: T, stop: T, size: Annotated[T, schema(min=1)]) -> "Line[T]":
    return Line(start=start, stop=stop, step=(stop - start) / (size - 1))


@dataclass
class Concat(Drawing[T]):
    left: Drawing[T]
    right: Drawing[T]

    async def points(self) -> AsyncIterable[T]:
        async for point in self.left.points():
            yield point
        async for point in self.right.points():
            yield point


def echo(drawing: Drawing[str] = None) -> Optional[Drawing[str]]:
    return drawing


drawing_schema = graphql_schema(query=[echo])
assert (
    graphql.utilities.print_schema(drawing_schema)
    == """\
type Query {
  echo(drawing: DrawingStrInput): DrawingStr
}

type DrawingStr {
  Line: LineStr
  Concat: ConcatStr
}

type LineStr {
  start: String!
  stop: String!
  step: String!
}

type ConcatStr {
  left: DrawingStr!
  right: DrawingStr!
}

input DrawingStrInput {
  Line: LineStrInput
  Concat: ConcatStrInput
}

input LineStrInput {
  start: String!
  stop: String!
  step: String! = "1"
}

input ConcatStrInput {
  left: DrawingStrInput!
  right: DrawingStrInput!
}
"""
)
```

Genericity of tagged union conversion is handled using `with_params`. It assumes all subclasses have the same generic parameters.
I've used generic `type_name` pattern, passing a function to build the type name by suffixing its generic arguments; this function is not very robust and need of course to be customized according to your need.

**Comment by callumforrester** [comment]
Thanks @wyfo this looks good, although it doesn't create the alternative constructor because `rec_subclasses` returns `Line` rather than `Line[~T]`.

**Comment by callumforrester** [comment]
I have added it back in by rewriting `rec_subclasses` as so, but I'm wondering if there is a better way:
```python
def rec_subclasses(cls: type) -> Iterator[type]:
    """Recursive implementation of type.__subclasses__"""
    for sub_cls in cls.__subclasses__():
        params = tuple(getattr(sub_cls, "__parameters__", ()))
        if params:
            parametrized = sub_cls[params]
            setattr(parametrized, "__name__", str(parametrized))
            yield sub_cls[params]
        else:
            yield sub_cls
        yield from rec_subclasses(sub_cls)
```

**Comment by wyfo** [comment]
> although it doesn't create the alternative constructor because rec_subclasses returns Line rather than Line[~T].

Yes, sorry, I've forgotten this part. But modifying `rec_subclasses` is not the best way to do it. Indeed, if two constructors return `Line[T]` and `Line[U]`, you will not retrieve both of them with your implementation.

The key of all constructors in the dictionary must be the same, that's why I rather suggest to fix `alternative_constructor`, for example like this:
```python
# Don't forget to import `get_origin` from `typing`
def alternative_constructor(func: Func) -> Func:
    return_type = get_type_hints(func)["return"]
    _alternative_constructors[get_origin(return_type) or return_type].append(func)
    return func
```
